
CREATE TABLE admins (
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
login VARCHAR(254) NOT NULL,
passwd VARCHAR(254) NOT NULL
) ENGINE = INNODB;

CREATE TABLE  players (
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nom VARCHAR(254) NOT NULL,
prenom VARCHAR(254) NOT NULL,
age VARCHAR(10) NOT NULL,
tel VARCHAR( 10 ) NOT NULL ,
email VARCHAR(254) NOT NULL,
vote VARCHAR(10) NOT NULL,
ami VARCHAR(10),
createdat DATETIME NOT NULL
) ENGINE = INNODB;

CREATE TABLE questions (
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
numetape BIGINT NOT NULL,
vote VARCHAR(10) NOT NULL,
createdat DATETIME NOT NULL
) ENGINE = INNODB;
